"""empty message

Revision ID: 88b6d6422429
Revises: 9ecc6cefdb96
Create Date: 2021-12-12 22:23:47.893853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b6d6422429'
down_revision = '9ecc6cefdb96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('nickname', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'nickname')
    # ### end Alembic commands ###
