"""empty message

Revision ID: fb1199b7a2da
Revises: 88b6d6422429
Create Date: 2021-12-12 22:24:29.407929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1199b7a2da'
down_revision = '88b6d6422429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('nickname', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
